export { default as Discovery } from './Discovery'
export { default as Profile } from './Profile'
export { default as Search } from './Search'
export { default as ArtistReleases } from './ArtistReleases'
export { default as ArtistRelease } from './ArtistRelease'
export { default as SignUp } from './SignUp'
export { default as SignIn } from './SignIn'
