# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "minipopsnative.xcodeproj")
    get_certificates
    get_provisioning_profile
    build_app(scheme: "minipopsnative")
    upload_to_testflight
  end
end

platform :ios do
    lane :appcenterPost do |options|
        ENV[‘FASTLANE_PASSWORD’] = options[:password]
        ENV[‘FASTLANE_USERNAME’] = options[:user]
        increment_build_number(xcodeproj: "minipopsnative.xcodeproj")
        get_certificates
        get_provisioning_profile
        upload_to_testflight(ipa: options[:ipa])
        end
end
